In [109]:
#import necessary libraries

import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt


In [110]:
##load data

movies = pd.read_csv('data/movies.csv')
credits = pd.read_csv('data/credits.csv')


In [111]:
# print first five line

credits.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [112]:
movies.shape

(4803, 20)

In [113]:
credits.shape

(4803, 4)

In [114]:
# merging two datasets
new_movies = movies.merge(credits, on = 'title')
new_movies.head(2)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   

                                production_companies  ... runtime  \
0  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   169.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title vote_average vote_count movie_id  \
0                                    Avatar          7.2      11800    19995   
1  Pirates of the Caribbean: At World's End          6.9       4500      285   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  

[2 rows x 23 columns]

In [115]:
##view information about dataset
new_movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4809 non-null   int64  
 1   genres                4809 non-null   object 
 2   homepage              1713 non-null   object 
 3   id                    4809 non-null   int64  
 4   keywords              4809 non-null   object 
 5   original_language     4809 non-null   object 
 6   original_title        4809 non-null   object 
 7   overview              4806 non-null   object 
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object 
 10  production_countries  4809 non-null   object 
 11  release_date          4808 non-null   object 
 12  revenue               4809 non-null   int64  
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object 
 15  status               

In [116]:
#view columns in dataset
new_movies.columns


Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [117]:
#removing unnecessary columns  
new_movies = new_movies.drop(['id','budget', 'homepage', 'original_language','original_title', 'popularity', 'production_companies', 'production_countries','release_date', 'revenue', 'spoken_languages', 'status', 'tagline', 'vote_count' , 'runtime' ], axis=1)

In [118]:
#re arranging columns
new_movies = new_movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew', 'vote_average']]

In [119]:
#checking for null values
new_movies.isnull().sum()

#drop null value rows
new_movies.dropna(inplace =True)
print(new_movies.isnull().sum())



movie_id        0
title           0
overview        0
genres          0
keywords        0
cast            0
crew            0
vote_average    0
dtype: int64


In [120]:
##checking for duplicate values
new_movies.duplicated().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of 0       False
1       False
2       False
3       False
4       False
        ...  
4804    False
4805    False
4806    False
4807    False
4808    False
Length: 4806, dtype: bool>

Extracting necessary data from mongo db objects

In [121]:
#ast library convert string into lists
import ast

def convert_genres(txt):
    lst = []
    
    for i in ast.literal_eval(txt): #method to convert string to list
        
        lst.append(i['name'])
    
    return lst


    

In [122]:
def convert_cast(txt):
    lst = []
    count = 0
    for i in ast.literal_eval(txt): #method to convert string to list
        
        if count< 3:
            lst.append(i['name'])
            count += 1
    
    return lst

In [123]:
def convert_crew(txt):
    lst = []
    
    for i in ast.literal_eval(txt): #method to convert string to list
        
        if i['job'] == 'Director':
            lst.append(i['name'])
            break
    return lst

In [124]:
#checking mongodb string for genre
new_movies.iloc[0]['genres']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [125]:
new_movies.head(2)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   

                                                crew  vote_average  
0  [{"credit_id": "52fe48009251416c750aca23", "de...           7.2  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...           6.9

In [126]:
# applying above created function to all relevant columns and all rows
new_movies['genres'] = new_movies['genres'].apply(convert_genres)
new_movies['cast'] = new_movies['cast'].apply(convert_cast)
new_movies['keywords'] = new_movies['keywords'].apply(convert_genres)
new_movies['crew'] = new_movies['crew'].apply(convert_crew)
new_movies['overview'] = new_movies['overview'].apply(lambda x : x.split())

In [127]:
new_movies.head(2)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   

                                               cast              crew  \
0  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   [James Cameron]   
1     [Johnny Depp, Orlando Bloom, Keira Knightley]  [Gore Verbinski]   

   vote_average  
0           7.2  
1           6.9

In [130]:
# combining several columns to create common string
new_movies['tags'] = new_movies['overview'] + new_movies['genres'] + new_movies['keywords'] + new_movies['cast'] + new_movies['crew']

# re-arranging dataset columns
new_movies = new_movies[['movie_id','title','tags']]
new_movies.head(2)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                                tags  
0  [In, the, 22nd, century,, a, paraplegic, Marin...  
1  [Captain, Barbossa,, long, believed, to, be, d...

In [131]:
# converting the list of strings into a single string
new_movies['tags'] = new_movies['tags'].apply(lambda x : ' '.join(x))
new_movies.head(2)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                                tags  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...

In [132]:
# convert data in 'tags' column to lowercase
new_movies['tags'] = new_movies['tags'].apply(lambda x :x.lower())
new_movies.head(2)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                                tags  
0  in the 22nd century, a paraplegic marine is di...  
1  captain barbossa, long believed to be dead, ha...

In [133]:
new_movies.iloc[0]['tags']

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy science fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d sam worthington zoe saldana sigourney weaver james cameron'

In [134]:
#import PorterStemmer for stemming
import nltk
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

In [135]:
##function to stem all the words 
def stemming(txt):
    lst = []
    
    for word in txt.split():
        lst.append(stemmer.stem(word))
         
    return ' '.join(lst)

In [136]:
##apply above function to all rows in dataset
new_movies['tags'] = new_movies['tags'].apply(stemming)

In [137]:
new_movies.iloc[0]['tags']

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi scienc fiction cultur clash futur space war space coloni societi space travel futurist romanc space alien tribe alien planet cgi marin soldier battl love affair anti war power relat mind and soul 3d sam worthington zoe saldana sigourney weaver jame cameron'

In [138]:
#import vectorizer to calculate tf-idf values of each term
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features = 5000, stop_words = 'english')


In [139]:
#apply vectorizer to dataset
vect = vectorizer.fit_transform(new_movies['tags']).toarray()
print(vect)
vect.shape

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


(4806, 5000)

In [140]:
# import necessary function to calculate cosine_similarity
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vect)

In [141]:
print(similarity)
similarity.shape

[[1.         0.02199149 0.03587852 ... 0.02199518 0.02772966 0.        ]
 [0.02199149 1.         0.01073806 ... 0.0201334  0.         0.00496068]
 [0.03587852 0.01073806 1.         ... 0.01367133 0.07050887 0.        ]
 ...
 [0.02199518 0.0201334  0.01367133 ... 1.         0.01849843 0.0226023 ]
 [0.02772966 0.         0.07050887 ... 0.01849843 1.         0.01664042]
 [0.         0.00496068 0.         ... 0.0226023  0.01664042 1.        ]]


(4806, 4806)

In [142]:
# function to recommend suitable movies in descending order 

def recommend (movie):
    index = new_movies[new_movies['title']== movie].index[0]
    distance = sorted(list(enumerate(similarity[index])),reverse=True, key = lambda x:x[1])

    for i in distance[0:10]:
        print(new_movies.iloc[i[0]].title)
                       

In [143]:
recommend('Titanic')

Titanic
Ghost Ship
Poseidon
The Notebook
Romance & Cigarettes
Triangle
Captain Phillips
Life of Pi
Pirates of the Caribbean: On Stranger Tides
The Black Hole


In [144]:
##save model for later use
import pickle

pickle.dump(new_movies, open('artifacts/movie_later.pkl', 'wb'))
pickle.dump(similarity, open('artifacts/similarity.pkl', 'wb'))